version: '3'
volumes:
  dados:
networks:
  banco:
  web:
  fila:
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - dados:/var/lib/postbresql/data
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco
  frontend:
    image: nginx:1.13
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx/default.config:/etc/nginx/conf.d/default.conf
    ports:
      - 1227:80
    networks:
      - web
    depends_on:
      - app
  app:
    build: app
    networks:
      - banco
      - web
      - fila
    depends_on:
      - db
      - queue
  queue:
    image: redis:3.2
    networks:
      - fila
  worker:
    build: worker
    scale: 3
    networks:
      - fila
    depends_on:
      - queue
