name: Prettify Code

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  prettier:
    name: Prettify code
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Prettify code
        # Why i'm not using creyD version: https://github.com/creyD/prettier_action/pull/44
        uses: suda/prettier_action@v3.4-rc.1
        with:
          prettier_options:
            --write ./**/*.{js,jsx,ts,tsx,md,json,html,css,yml,scss,java,xml,yaml,}
          same_commit: false
          only_changed: false
          prettier_plugins:
            '@arthurfiorette/prettier-config prettier-plugin-java @prettier/plugin-xml'
          commit_message: 'style(prettier): prettified code'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Linux node_modules path to require() global modules
          NODE_PATH: /usr/local/lib/node_modules
